/**
 * Forms Query Layer
 * Contains all form-related queries
 *
 * Usage:
 * import { useGetFormsQuery, useGetFormQuery } from '@/shared/api/queries/forms'
 *
 * This file will be auto-generated by codegen from forms.graphql
 * Currently imports from generated endpoints
 */

export { useGetFormsQuery, useGetFormQuery } from '../enhancedApi';
