/**
 * Responses Query Layer
 * Contains all response-related queries
 *
 * Usage:
 * import { useGetResponsesQuery } from '@/shared/api/queries/responses'
 *
 * This file will be auto-generated by codegen from forms.graphql
 * Currently imports from generated endpoints
 */

export { useGetResponsesQuery } from '../enhancedApi';
